### ISSUE TITLE
fruit trees keep growing no matter the season you are in

### ISSUE THREAD

**Issue by matheusvingadouro** [Darkorg69/Serene-Seasons-Pams-HarvestCraft-2-Trees-Compat#1]
that's it, they keep growing naturally... try "/gamerule randomtickspeed 3000" in winter season

**Comment by Darkorg69** [comment]
Cannot reproduce problem.

Probably you have allowed crops to grow out of season from Serene Seasons configuration.

If you still have a problem, open a new issue.
